name: Franklin Madison

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # prevents extra Cypress installation progress messages
      CI: 1
      SPLIT: ${{ strategy.job-total }}
      SPLIT_INDEX: ${{ strategy.job-index }}
      # avoid warnings like "tput: No value for $TERM and no -T specified"
      TERM: xterm
    container: cypress/browsers:node16.5.0-chrome94-ff93
    strategy:
      matrix:
        # run copies of the current job in parallel
        ci_node_total: [2]
        ci_node_index: [0, 1]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run test:stage
        env:
          CI: true
          
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "channel": "#cypress-test",
              "attachments": [
                {
                  "fallback": "Cypress Test Report",
                  "color": "#36a64f",
                  "pretext": "Cypress Test Report",
                  "title": "View the Cypress Test Report",
                  "title_link": "${{ steps.upload.outputs.artifact_url }}",
                  "text": "The Cypress tests have completed. Click the link above to view the detailed report.",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://platform.slack-edge.com/img/default_application_icon.png",
                  "ts": ${{ steps.date.outputs.timestamp }}
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
