name: Franklin Madison

on:
  push:
    branches: [main]

jobs:
  # Node Environment
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: [1, 2] # Use 2 parallel instances
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run test:node
        env:
          CI: true

      # After the test run completes, store videos and any screenshots
      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

      - name: Upload Videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`


#   # Stage Environment
#   test-stage:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Install Dependencies
#         run: npm install

#       - name: Run Cypress Tests
#         run: npm run test:stage
#         env:
#           CI: true
      

#   # Production Environment
#   test-prod:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Install Dependencies
#         run: npm install

#       - name: Run Cypress Tests
#         run: npm run test:prod
#         env:
#           CI: true
       

#   # VR Test (Prod)
#   prod-vr-percy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3

#       - name: Install Dependencies
#         run: npm install

#       - name: Run VR Tests with Percy
#         run: npm run prod-vr-percy
#         env:
#           CI: true
        
